CREATE USER 'idyalUser'@'%' IDENTIFIED BY  '***';

GRANT ALL PRIVILEGES ON * . * TO  'idyalUser'@'localhost'
IDENTIFIED BY  '***'
WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

GRANT ALL PRIVILEGES ON  `framework` . * TO  'idyalUser'@'localhost';